#!/bin/bash -l
#SBATCH --job-name="weighter_loss_lars_multistep"
#SBATCH --account="s1054"
#SBATCH --mail-type=ALL
#SBATCH --mail-user=zihengq@comp.nus.edu.sg
#SBATCH --time=10:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=normal
#SBATCH --constraint=gpu
#SBATCH --hint=nomultithread

module load daint-gpu
module load PyTorch

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun \
python3 -u onecycle_cifar_res_weighted.py \
--optimizer lars --lr 1 --weighted-loss 1 \
> ${SLURM_JOBID}.out 2> ${SLURM_JOBID}.err